In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import pickle

In [2]:
df = pd.read_csv('census.csv')

In [3]:
df.head(4)

age         workclass  final-weight  education  education-num  \
0   39         State-gov         77516  Bachelors             13   
1   50  Self-emp-not-inc         83311  Bachelors             13   
2   38           Private        215646    HS-grad              9   
3   53           Private        234721       11th              7   

       marital-status         occupation   relationship   race   sex  \
0       Never-married       Adm-clerical  Not-in-family  White  Male   
1  Married-civ-spouse    Exec-managerial        Husband  White  Male   
2            Divorced  Handlers-cleaners  Not-in-family  White  Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black  Male   

   capital-gain  capital-loos  hour-per-week native-country income  
0          2174             0             40  United-States  <=50K  
1             0             0             13  United-States  <=50K  
2             0             0             40  United-States  <=50K  
3             0             0             40  United-States  <=50K

In [4]:
df.columns

Index(['age', 'workclass', 'final-weight', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loos', 'hour-per-week', 'native-country',
       'income'],
      dtype='object')

In [5]:
df.columns   = [    'age', 'workclass', 'final_weight', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loos', 'hour_per_week', 'native_country',
       'income' ]

In [6]:
df_ = df.drop(['income', 'native_country', 'capital_gain', 'capital_loos'], axis = 1)

In [7]:
df_target = df.drop(['age', 'workclass', 'final_weight', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loos', 'hour_per_week', 'native_country'], axis = 1)

In [8]:
df_.columns

Index(['age', 'workclass', 'final_weight', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'hour_per_week'],
      dtype='object')

In [9]:
df_.isnull().sum()

age               0
workclass         0
final_weight      0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
hour_per_week     0
dtype: int64

In [10]:
np.unique(df_['age'],return_counts = True) #Minmax

(array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 90]),
 array([395, 550, 712, 753, 720, 765, 877, 798, 841, 785, 835, 867, 813,
        861, 888, 828, 875, 886, 876, 898, 858, 827, 816, 794, 808, 780,
        770, 724, 734, 737, 708, 543, 577, 602, 595, 478, 464, 415, 419,
        366, 358, 366, 355, 312, 300, 258, 230, 208, 178, 150, 151, 120,
        108,  89,  72,  67,  64,  51,  45,  46,  29,  23,  22,  22,  20,
         12,   6,  10,   3,   1,   1,   3,  43]))

In [11]:
np.unique(df_['workclass'],return_counts = True)

(array(['?', 'Federal-gov', 'Local-gov', 'Never-worked', 'Private',
        'Self-emp-inc', 'Self-emp-not-inc', 'State-gov', 'Without-pay'],
       dtype=object),
 array([ 1836,   960,  2093,     7, 22696,  1116,  2541,  1298,    14]))

In [12]:
np.unique(df_['final_weight'],return_counts = True)  #Minmax

(array([  12285,   13769,   14878, ..., 1366120, 1455435, 1484705]),
 array([1, 1, 1, ..., 1, 1, 1]))

In [13]:
np.unique(df_['education'],return_counts = True)

(array(['10th', '11th', '12th', '1st-4th', '5th-6th', '7th-8th', '9th',
        'Assoc-acdm', 'Assoc-voc', 'Bachelors', 'Doctorate', 'HS-grad',
        'Masters', 'Preschool', 'Prof-school', 'Some-college'],
       dtype=object),
 array([  933,  1175,   433,   168,   333,   646,   514,  1067,  1382,
         5355,   413, 10501,  1723,    51,   576,  7291]))

In [14]:
np.unique(df_['education_num'],return_counts = True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 array([   51,   168,   333,   646,   514,   933,  1175,   433, 10501,
         7291,  1382,  1067,  5355,  1723,   576,   413]))

In [15]:
np.unique(df_['marital_status'],return_counts = True)  

(array(['Divorced', 'Married-AF-spouse', 'Married-civ-spouse',
        'Married-spouse-absent', 'Never-married', 'Separated', 'Widowed'],
       dtype=object),
 array([ 4443,    23, 14976,   418, 10683,  1025,   993]))

In [16]:
np.unique(df_['occupation'],return_counts = True)

(array(['?', 'Adm-clerical', 'Armed-Forces', 'Craft-repair',
        'Exec-managerial', 'Farming-fishing', 'Handlers-cleaners',
        'Machine-op-inspct', 'Other-service', 'Priv-house-serv',
        'Prof-specialty', 'Protective-serv', 'Sales', 'Tech-support',
        'Transport-moving'], dtype=object),
 array([1843, 3770,    9, 4099, 4066,  994, 1370, 2002, 3295,  149, 4140,
         649, 3650,  928, 1597]))

In [17]:
np.unique(df_['relationship'],return_counts = True)

(array(['Husband', 'Not-in-family', 'Other-relative', 'Own-child',
        'Unmarried', 'Wife'], dtype=object),
 array([13193,  8305,   981,  5068,  3446,  1568]))

In [18]:
np.unique(df_['race'],return_counts = True)

(array(['Amer-Indian-Eskimo', 'Asian-Pac-Islander', 'Black', 'Other',
        'White'], dtype=object),
 array([  311,  1039,  3124,   271, 27816]))

In [19]:
np.unique(df_['sex'],return_counts = True)

(array(['Female', 'Male'], dtype=object), array([10771, 21790]))

#Criando linhas Artificiais

In [20]:
np.unique(df_target['income'], return_counts = True)

(array(['<=50K', '>50K'], dtype=object), array([24720,  7841]))

In [21]:
def tipo_target(line):
    if line == '<=50K':
        return '0'
    elif line == '>50K':
        return '1'

In [22]:
df_target['target']   = df_target['income'].apply(lambda x: tipo_target(x))

In [109]:
df_target.sample(4)

target
1683       0
20157      0
6111       1
32541      0

In [24]:
df_target.columns

Index(['income', 'target'], dtype='object')

In [25]:
df_target = df_target.drop(['income'], axis = True)

In [26]:
df_target.sample(4)

target
2603       1
31607      0
5772       0
11218      0

In [27]:
np.unique(df_['sex'], return_counts = True)

(array(['Female', 'Male'], dtype=object), array([10771, 21790]))

In [28]:
def tipo_Sex(line):
    if line == 'Female':
        return 'Female'
    elif line == 'Male':
        return 'Male'

In [29]:
df_['sex_']   = df_['sex'].apply(lambda x: tipo_Sex(x))

In [30]:
df_sex = pd.get_dummies(df['sex'], dummy_na=True)

In [31]:
df_sex.sample(3)

Female  Male  NaN
32435       0     1    0
21423       0     1    0
16268       0     1    0

In [33]:
df_sex.columns

Index(['Female', 'Male', nan], dtype='object')

In [34]:
df_sex.columns   = [ 'Female', 'Male', 'No_def_sex' ]

In [35]:
df_sex = df_sex.drop(['No_def_sex'], axis = 1)

In [36]:
df_menu = df_

In [37]:
df_menu = pd.concat([df_menu, df_sex ], axis=1, join="inner")

In [38]:
df_menu.head(4)

age         workclass  final_weight  education  education_num  \
0   39         State-gov         77516  Bachelors             13   
1   50  Self-emp-not-inc         83311  Bachelors             13   
2   38           Private        215646    HS-grad              9   
3   53           Private        234721       11th              7   

       marital_status         occupation   relationship   race   sex  \
0       Never-married       Adm-clerical  Not-in-family  White  Male   
1  Married-civ-spouse    Exec-managerial        Husband  White  Male   
2            Divorced  Handlers-cleaners  Not-in-family  White  Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black  Male   

   hour_per_week  sex_  Female  Male  
0             40  Male       0     1  
1             13  Male       0     1  
2             40  Male       0     1  
3             40  Male       0     1

In [39]:
df_menu = df_menu.drop(['sex', 'sex_'], axis = 1)

In [40]:
df_menu.columns

Index(['age', 'workclass', 'final_weight', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'hour_per_week',
       'Female', 'Male'],
      dtype='object')

In [41]:
np.unique(df_['workclass'], return_counts = True)

(array(['?', 'Federal-gov', 'Local-gov', 'Never-worked', 'Private',
        'Self-emp-inc', 'Self-emp-not-inc', 'State-gov', 'Without-pay'],
       dtype=object),
 array([ 1836,   960,  2093,     7, 22696,  1116,  2541,  1298,    14]))

In [42]:
def tipo_Work(line):
    if line == '?' :
        return 'desempregado'
    elif line == 'Federal-gov' :
        return 'Federal-gov'
    elif line == 'Local-gov' :
        return 'Local-gov'
    elif line == 'Never-worked' :
        return 'Never-worked'
    elif line == 'Private' :
        return 'Private'
    elif line == 'Self-emp-inc' :
        return 'Self-emp-inc'
    elif line == 'Self-emp-not-inc' :
        return 'Self-emp-not-inc'
    elif line == 'State-gov' :
        return 'State-gov'
    elif line == 'Without-pay' :
        return 'Without-pay'
    else :
        return ''

In [43]:
df_['workclass_']   = df_['workclass'].apply(lambda x: tipo_Work(x))

In [44]:
df_workclass = pd.get_dummies(df_['workclass_'], dummy_na=True)

In [45]:
df_workclass.columns

Index([     'Federal-gov',        'Local-gov',     'Never-worked',
                'Private',     'Self-emp-inc', 'Self-emp-not-inc',
              'State-gov',      'Without-pay',     'desempregado',
                      nan],
      dtype='object')

In [46]:
df_workclass.columns   = [ 'Federal_gov',        'Local_gov',     'Never_worked',
                'Private',     'Self_emp_inc', 'Self_emp_not_inc',
              'State_gov',      'Without_pay',     'desempregado', 'No_def_workclass' ]

In [47]:
df_workclass = df_workclass.drop(['No_def_workclass'], axis = 1)

In [48]:
df_menu = pd.concat([df_menu, df_workclass ], axis=1, join="inner")

In [49]:
df_menu

age         workclass  final_weight   education  education_num  \
0       39         State-gov         77516   Bachelors             13   
1       50  Self-emp-not-inc         83311   Bachelors             13   
2       38           Private        215646     HS-grad              9   
3       53           Private        234721        11th              7   
4       28           Private        338409   Bachelors             13   
...    ...               ...           ...         ...            ...   
32556   27           Private        257302  Assoc-acdm             12   
32557   40           Private        154374     HS-grad              9   
32558   58           Private        151910     HS-grad              9   
32559   22           Private        201490     HS-grad              9   
32560   52      Self-emp-inc        287927     HS-grad              9   

           marital_status         occupation   relationship   race  \
0           Never-married       Adm-clerical  Not-in-family  White   
1      Married-civ-spouse    Exec-managerial        Husband  White   
2                Divorced  Handlers-cleaners  Not-in-family  White   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black   
4      Married-civ-spouse     Prof-specialty           Wife  Black   
...                   ...                ...            ...    ...   
32556  Married-civ-spouse       Tech-support           Wife  White   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White   
32558             Widowed       Adm-clerical      Unmarried  White   
32559       Never-married       Adm-clerical      Own-child  White   
32560  Married-civ-spouse    Exec-managerial           Wife  White   

       hour_per_week  ...  Male  Federal-gov  Local-gov  Never-worked  \
0                 40  ...     1            0          0             0   
1                 13  ...     1            0          0             0   
2                 40  ...     1            0          0             0   
3                 40  ...     1            0          0             0   
4                 40  ...     0            0          0             0   
...              ...  ...   ...          ...        ...           ...   
32556             38  ...     0            0          0             0   
32557             40  ...     1            0          0             0   
32558             40  ...     0            0          0             0   
32559             20  ...     1            0          0             0   
32560             40  ...     0            0          0             0   

       Private  Self-emp-inc  Self-emp-not-inc  State-gov  Without-pay  \
0            0             0                 0          1            0   
1            0             0                 1          0            0   
2            1             0                 0          0            0   
3            1             0                 0          0            0   
4            1             0                 0          0            0   
...        ...           ...               ...        ...          ...   
32556        1             0                 0          0            0   
32557        1             0                 0          0            0   
32558        1             0                 0          0            0   
32559        1             0                 0          0            0   
32560        0             1                 0          0            0   

       desempregado  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
...             ...  
32556             0  
32557             0  
32558             0  
32559             0  
32560             0  

[32561 rows x 21 columns]

In [50]:
df_.columns

Index(['age', 'workclass', 'final_weight', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'hour_per_week', 'sex_', 'workclass_'],
      dtype='object')

In [51]:
np.unique(df_['education'], return_counts = True)

(array(['10th', '11th', '12th', '1st-4th', '5th-6th', '7th-8th', '9th',
        'Assoc-acdm', 'Assoc-voc', 'Bachelors', 'Doctorate', 'HS-grad',
        'Masters', 'Preschool', 'Prof-school', 'Some-college'],
       dtype=object),
 array([  933,  1175,   433,   168,   333,   646,   514,  1067,  1382,
         5355,   413, 10501,  1723,    51,   576,  7291]))

In [52]:
def tipo_education(line):
    if line == '10th' :
        return '10th'
    elif line == '11th' :
        return '11th'
    elif line == '12th' :
        return '12th'
    elif line == '1st-4th' :
        return '1st-4th'
    elif line == '5th-6th' :
        return '5th-6th'
    elif line == '7th-8th' :
        return '7th-8th'
    elif line == '9th' :
        return '9th'
    elif line == 'Assoc-acdm' :
        return 'Assoc-acdm'
    elif line == 'Assoc-voc' :
        return 'Assoc-voc'
    elif line == 'Bachelors' :
        return 'Bachelors'
    elif line == 'Doctorate' :
        return 'Doctorate'
    elif line == 'HS-grad' :
        return 'HS-grad'
    elif line == 'Masters' :
        return 'Masters'
    elif line == 'Preschool' :
        return 'Preschool'
    elif line == 'Prof-school' :
        return 'Prof-school'
    elif line == 'Some-college' :
        return 'Some-college'

In [53]:
df_['education_']   = df_['education'].apply(lambda x: tipo_education(x))
df_workclass = pd.get_dummies(df_['education_'], dummy_na=True)

In [54]:
df_workclass.columns

Index([        '10th',         '11th',         '12th',      '1st-4th',
            '5th-6th',      '7th-8th',          '9th',   'Assoc-acdm',
          'Assoc-voc',    'Bachelors',    'Doctorate',      'HS-grad',
            'Masters',    'Preschool',  'Prof-school', 'Some-college',
                  nan],
      dtype='object')

In [55]:
df_workclass.columns   = [  '10th',         '11th',         '12th',      '1st_4th',
            '5th_6th',      '7th_8th',          '9th',   'Assoc_acdm',
          'Assoc_voc',    'Bachelors',    'Doctorate',      'HS_grad',
            'Masters',    'Preschool',  'Prof_school', 'Some_college','No_def_education' ]


In [56]:
df_workclass = df_workclass.drop(['No_def_education'], axis = 1)
df_menu = pd.concat([df_menu, df_workclass ], axis=1, join="inner")

In [57]:
df_menu

age         workclass  final_weight   education  education_num  \
0       39         State-gov         77516   Bachelors             13   
1       50  Self-emp-not-inc         83311   Bachelors             13   
2       38           Private        215646     HS-grad              9   
3       53           Private        234721        11th              7   
4       28           Private        338409   Bachelors             13   
...    ...               ...           ...         ...            ...   
32556   27           Private        257302  Assoc-acdm             12   
32557   40           Private        154374     HS-grad              9   
32558   58           Private        151910     HS-grad              9   
32559   22           Private        201490     HS-grad              9   
32560   52      Self-emp-inc        287927     HS-grad              9   

           marital_status         occupation   relationship   race  \
0           Never-married       Adm-clerical  Not-in-family  White   
1      Married-civ-spouse    Exec-managerial        Husband  White   
2                Divorced  Handlers-cleaners  Not-in-family  White   
3      Married-civ-spouse  Handlers-cleaners        Husband  Black   
4      Married-civ-spouse     Prof-specialty           Wife  Black   
...                   ...                ...            ...    ...   
32556  Married-civ-spouse       Tech-support           Wife  White   
32557  Married-civ-spouse  Machine-op-inspct        Husband  White   
32558             Widowed       Adm-clerical      Unmarried  White   
32559       Never-married       Adm-clerical      Own-child  White   
32560  Married-civ-spouse    Exec-managerial           Wife  White   

       hour_per_week  ...  9th  Assoc-acdm  Assoc-voc  Bachelors  Doctorate  \
0                 40  ...    0           0          0          1          0   
1                 13  ...    0           0          0          1          0   
2                 40  ...    0           0          0          0          0   
3                 40  ...    0           0          0          0          0   
4                 40  ...    0           0          0          1          0   
...              ...  ...  ...         ...        ...        ...        ...   
32556             38  ...    0           1          0          0          0   
32557             40  ...    0           0          0          0          0   
32558             40  ...    0           0          0          0          0   
32559             20  ...    0           0          0          0          0   
32560             40  ...    0           0          0          0          0   

       HS-grad  Masters  Preschool  Prof-school  Some-college  
0            0        0          0            0             0  
1            0        0          0            0             0  
2            1        0          0            0             0  
3            0        0          0            0             0  
4            0        0          0            0             0  
...        ...      ...        ...          ...           ...  
32556        0        0          0            0             0  
32557        1        0          0            0             0  
32558        1        0          0            0             0  
32559        1        0          0            0             0  
32560        1        0          0            0             0  

[32561 rows x 37 columns]

In [58]:
np.unique(df['race'], return_counts = True)

(array(['Amer-Indian-Eskimo', 'Asian-Pac-Islander', 'Black', 'Other',
        'White'], dtype=object),
 array([  311,  1039,  3124,   271, 27816]))

In [59]:
def tipo_race(line):
    if line == 'Amer-Indian-Eskimo' :
        return 'Amer-Indian-Eskimo'
    elif line == 'Asian-Pac-Islander' :
        return 'Asian-Pac-Islander'
    elif line == 'Black' :
        return 'Black'
    elif line == 'Other' :
        return 'Other'
    elif line == 'White' :
        return 'White'

In [60]:
df_['race_']   = df_['race'].apply(lambda x: tipo_race(x))
df_race = pd.get_dummies(df_['race_'], dummy_na=True)

In [61]:
df_race.columns

Index(['Amer-Indian-Eskimo', 'Asian-Pac-Islander', 'Black', 'Other', 'White',
       nan],
      dtype='object')

In [62]:
df_race.columns   = [  'Amer_Indian_Eskimo', 'Asian_Pac_Islander', 'Black', 'Other', 'White','No_def_race' ]


In [63]:
df_race = df_race.drop(['No_def_race'], axis = 1)
df_menu = pd.concat([df_menu, df_race ], axis=1, join="inner")

In [64]:
df_menu = df_menu.drop(['education', 'race', 'workclass'], axis = 1)

In [65]:
df_menu

age  final_weight  education_num      marital_status  \
0       39         77516             13       Never-married   
1       50         83311             13  Married-civ-spouse   
2       38        215646              9            Divorced   
3       53        234721              7  Married-civ-spouse   
4       28        338409             13  Married-civ-spouse   
...    ...           ...            ...                 ...   
32556   27        257302             12  Married-civ-spouse   
32557   40        154374              9  Married-civ-spouse   
32558   58        151910              9             Widowed   
32559   22        201490              9       Never-married   
32560   52        287927              9  Married-civ-spouse   

              occupation   relationship  hour_per_week  Female  Male  \
0           Adm-clerical  Not-in-family             40       0     1   
1        Exec-managerial        Husband             13       0     1   
2      Handlers-cleaners  Not-in-family             40       0     1   
3      Handlers-cleaners        Husband             40       0     1   
4         Prof-specialty           Wife             40       1     0   
...                  ...            ...            ...     ...   ...   
32556       Tech-support           Wife             38       1     0   
32557  Machine-op-inspct        Husband             40       0     1   
32558       Adm-clerical      Unmarried             40       1     0   
32559       Adm-clerical      Own-child             20       0     1   
32560    Exec-managerial           Wife             40       1     0   

       Federal-gov  ...  HS-grad  Masters  Preschool  Prof-school  \
0                0  ...        0        0          0            0   
1                0  ...        0        0          0            0   
2                0  ...        1        0          0            0   
3                0  ...        0        0          0            0   
4                0  ...        0        0          0            0   
...            ...  ...      ...      ...        ...          ...   
32556            0  ...        0        0          0            0   
32557            0  ...        1        0          0            0   
32558            0  ...        1        0          0            0   
32559            0  ...        1        0          0            0   
32560            0  ...        1        0          0            0   

       Some-college  Amer-Indian-Eskimo  Asian-Pac-Islander  Black  Other  \
0                 0                   0                   0      0      0   
1                 0                   0                   0      0      0   
2                 0                   0                   0      0      0   
3                 0                   0                   0      1      0   
4                 0                   0                   0      1      0   
...             ...                 ...                 ...    ...    ...   
32556             0                   0                   0      0      0   
32557             0                   0                   0      0      0   
32558             0                   0                   0      0      0   
32559             0                   0                   0      0      0   
32560             0                   0                   0      0      0   

       White  
0          1  
1          1  
2          1  
3          0  
4          0  
...      ...  
32556      1  
32557      1  
32558      1  
32559      1  
32560      1  

[32561 rows x 39 columns]

In [66]:
np.unique(df['relationship'], return_counts = True)

(array(['Husband', 'Not-in-family', 'Other-relative', 'Own-child',
        'Unmarried', 'Wife'], dtype=object),
 array([13193,  8305,   981,  5068,  3446,  1568]))

In [67]:
def tipo_relationship(line):
    if line == 'Husband' :
        return 'Husband'
    elif line == 'Not-in-family' :
        return 'Not-in-family'
    elif line == 'Other-relative' :
        return 'Other-relative'
    elif line == 'Own-child' :
        return 'Own-child'
    elif line == 'Unmarried' :
        return 'Unmarried'
    elif line == 'Wife' :
        return 'Wife'

In [68]:
df_['relationship_']   = df_['relationship'].apply(lambda x: tipo_relationship(x))
df_relationship = pd.get_dummies(df_['relationship_'], dummy_na=True)

In [69]:
df_relationship.columns

Index([       'Husband',  'Not-in-family', 'Other-relative',      'Own-child',
            'Unmarried',           'Wife',              nan],
      dtype='object')

In [70]:
df_relationship.columns   = [ 'Husband',  'Not-in-family', 'Other-relative',      'Own-child',
            'Unmarried',           'Wife' ,'No_def_relationship' ]

In [71]:
df_relationship = df_relationship.drop(['No_def_relationship'], axis = 1)

In [72]:
df_menu = pd.concat([df_menu, df_relationship ], axis=1, join="inner")

In [73]:
np.unique(df['occupation'], return_counts = True)

(array(['?', 'Adm-clerical', 'Armed-Forces', 'Craft-repair',
        'Exec-managerial', 'Farming-fishing', 'Handlers-cleaners',
        'Machine-op-inspct', 'Other-service', 'Priv-house-serv',
        'Prof-specialty', 'Protective-serv', 'Sales', 'Tech-support',
        'Transport-moving'], dtype=object),
 array([1843, 3770,    9, 4099, 4066,  994, 1370, 2002, 3295,  149, 4140,
         649, 3650,  928, 1597]))

In [74]:
def tipo_occupation(line):
    if line == '?' :
        return 'Indefinido'
    elif line == 'Adm-clerical' :
        return 'Adm-clerical'
    elif line == 'Armed-Forces' :
        return 'Armed-Forces'
    elif line == 'Exec-managerial' :
        return 'Exec-managerial'
    elif line == 'Farming-fishing' :
        return 'Farming-fishing'
    elif line == 'Handlers-cleaners' :
        return 'Handlers-cleaners'
    elif line == 'Machine-op-inspct' :
        return 'Machine-op-inspct'
    elif line == 'Other-service' :
        return 'Other-service'
    elif line == 'Priv-house-serv' :
        return 'Priv-house-serv'
    elif line == 'Prof-specialty' :
        return 'Prof-specialty'
    elif line == 'Protective-serv' :
        return 'Protective-serv'
    elif line == 'Sales' :
        return 'Sales'
    elif line == 'Tech-support' :
        return 'Tech-support'
    elif line == 'Transport-moving' :
        return 'Transport-moving'

In [75]:
df_['occupation_']   = df_['occupation'].apply(lambda x: tipo_occupation(x))
df_occupation = pd.get_dummies(df_['occupation_'], dummy_na=True)

In [76]:
df_occupation.columns

Index([     'Adm-clerical',      'Armed-Forces',   'Exec-managerial',
         'Farming-fishing', 'Handlers-cleaners',        'Indefinido',
       'Machine-op-inspct',     'Other-service',   'Priv-house-serv',
          'Prof-specialty',   'Protective-serv',             'Sales',
            'Tech-support',  'Transport-moving',                 nan],
      dtype='object')

In [77]:
df_occupation.columns   = [    'Adm_clerical',      'Armed_Forces',   'Exec_managerial',
         'Farming-fishing', 'Handlers-cleaners',        'Indefinido',
       'Machine_op_inspct',     'Other_service',   'Priv_house_serv',
          'Prof_specialty',   'Protective_serv',             'Sales',
            'Tech_support',  'Transport_moving','No_def_occupation' ]

In [78]:
df_occupation = df_occupation.drop(['No_def_occupation'], axis = 1)
df_menu = pd.concat([df_menu, df_occupation ], axis=1, join="inner")

In [79]:
df_menu

age  final_weight  education_num      marital_status  \
0       39         77516             13       Never-married   
1       50         83311             13  Married-civ-spouse   
2       38        215646              9            Divorced   
3       53        234721              7  Married-civ-spouse   
4       28        338409             13  Married-civ-spouse   
...    ...           ...            ...                 ...   
32556   27        257302             12  Married-civ-spouse   
32557   40        154374              9  Married-civ-spouse   
32558   58        151910              9             Widowed   
32559   22        201490              9       Never-married   
32560   52        287927              9  Married-civ-spouse   

              occupation   relationship  hour_per_week  Female  Male  \
0           Adm-clerical  Not-in-family             40       0     1   
1        Exec-managerial        Husband             13       0     1   
2      Handlers-cleaners  Not-in-family             40       0     1   
3      Handlers-cleaners        Husband             40       0     1   
4         Prof-specialty           Wife             40       1     0   
...                  ...            ...            ...     ...   ...   
32556       Tech-support           Wife             38       1     0   
32557  Machine-op-inspct        Husband             40       0     1   
32558       Adm-clerical      Unmarried             40       1     0   
32559       Adm-clerical      Own-child             20       0     1   
32560    Exec-managerial           Wife             40       1     0   

       Federal-gov  ...  Handlers-cleaners  Indefinido  Machine-op-inspct  \
0                0  ...                  0           0                  0   
1                0  ...                  0           0                  0   
2                0  ...                  1           0                  0   
3                0  ...                  1           0                  0   
4                0  ...                  0           0                  0   
...            ...  ...                ...         ...                ...   
32556            0  ...                  0           0                  0   
32557            0  ...                  0           0                  1   
32558            0  ...                  0           0                  0   
32559            0  ...                  0           0                  0   
32560            0  ...                  0           0                  0   

       Other-service  Priv-house-serv  Prof-specialty  Protective-serv  Sales  \
0                  0                0               0                0      0   
1                  0                0               0                0      0   
2                  0                0               0                0      0   
3                  0                0               0                0      0   
4                  0                0               1                0      0   
...              ...              ...             ...              ...    ...   
32556              0                0               0                0      0   
32557              0                0               0                0      0   
32558              0                0               0                0      0   
32559              0                0               0                0      0   
32560              0                0               0                0      0   

       Tech-support  Transport-moving  
0                 0                 0  
1                 0                 0  
2                 0                 0  
3                 0                 0  
4                 0                 0  
...             ...               ...  
32556             1                 0  
32557             0                 0  
32558             0                 0  
32559             0                 0  
32560             0                 0  

[32561

In [80]:
np.unique(df_['marital_status'], return_counts = True)

(array(['Divorced', 'Married-AF-spouse', 'Married-civ-spouse',
        'Married-spouse-absent', 'Never-married', 'Separated', 'Widowed'],
       dtype=object),
 array([ 4443,    23, 14976,   418, 10683,  1025,   993]))

In [81]:
def tipo_marital_status(line):
    if line == 'Divorced' :
        return 'Divorced'
    elif line == 'Married-AF-spouse' :
        return 'Married-AF-spouse'
    elif line == 'Married-civ-spouse' :
        return 'Married-civ-spouse'
    elif line == 'Married-spouse-absent' :
        return 'Married-spouse-absent'
    elif line == 'Never-married' :
        return 'Never-married'
    elif line == 'Separated' :
        return 'Separated'
    elif line == 'Widowed' :
        return 'Widowed'

In [82]:
df_['marital_status']   = df_['marital_status'].apply(lambda x: tipo_marital_status(x))
df_marital_status = pd.get_dummies(df_['marital_status'], dummy_na=True)

In [83]:
df_marital_status.columns

Index([             'Divorced',     'Married-AF-spouse',
          'Married-civ-spouse', 'Married-spouse-absent',
               'Never-married',             'Separated',
                     'Widowed',                     nan],
      dtype='object')

In [84]:
df_marital_status.columns   = [    'Divorced',     'Married_AF_spouse',
          'Married_civ_spouse', 'Married_spouse_absent',
               'Never_married',             'Separated',
                     'Widowed','No_def_marital_status' ]

In [85]:
df_marital_status = df_marital_status.drop(['No_def_marital_status'], axis = 1)
df_menu = pd.concat([df_menu, df_marital_status ], axis=1, join="inner")

In [86]:
df_menu.columns

Index(['age', 'final_weight', 'education_num', 'marital_status', 'occupation',
       'relationship', 'hour_per_week', 'Female', 'Male', 'Federal-gov',
       'Local-gov', 'Never-worked', 'Private', 'Self-emp-inc',
       'Self-emp-not-inc', 'State-gov', 'Without-pay', 'desempregado', '10th',
       '11th', '12th', '1st-4th', '5th-6th', '7th-8th', '9th', 'Assoc-acdm',
       'Assoc-voc', 'Bachelors', 'Doctorate', 'HS-grad', 'Masters',
       'Preschool', 'Prof-school', 'Some-college', 'Amer-Indian-Eskimo',
       'Asian-Pac-Islander', 'Black', 'Other', 'White', 'Husband',
       'Not-in-family', 'Other-relative', 'Own-child', 'Unmarried', 'Wife',
       'Adm-clerical', 'Armed-Forces', 'Exec-managerial', 'Farming-fishing',
       'Handlers-cleaners', 'Indefinido', 'Machine-op-inspct', 'Other-service',
       'Priv-house-serv', 'Prof-specialty', 'Protective-serv', 'Sales',
       'Tech-support', 'Transport-moving', 'Divorced', 'Married_AF_spouse',
       'Married_civ_spouse', 'Married_sp

In [87]:
df_menu = df_menu.drop(['occupation','marital_status','relationship' ], axis = 1)


In [88]:
df_menu

age  final_weight  education_num  hour_per_week  Female  Male  \
0       39         77516             13             40       0     1   
1       50         83311             13             13       0     1   
2       38        215646              9             40       0     1   
3       53        234721              7             40       0     1   
4       28        338409             13             40       1     0   
...    ...           ...            ...            ...     ...   ...   
32556   27        257302             12             38       1     0   
32557   40        154374              9             40       0     1   
32558   58        151910              9             40       1     0   
32559   22        201490              9             20       0     1   
32560   52        287927              9             40       1     0   

       Federal-gov  Local-gov  Never-worked  Private  ...  Sales  \
0                0          0             0        0  ...      0   
1                0          0             0        0  ...      0   
2                0          0             0        1  ...      0   
3                0          0             0        1  ...      0   
4                0          0             0        1  ...      0   
...            ...        ...           ...      ...  ...    ...   
32556            0          0             0        1  ...      0   
32557            0          0             0        1  ...      0   
32558            0          0             0        1  ...      0   
32559            0          0             0        1  ...      0   
32560            0          0             0        0  ...      0   

       Tech-support  Transport-moving  Divorced  Married_AF_spouse  \
0                 0                 0         0                  0   
1                 0                 0         0                  0   
2                 0                 0         1                  0   
3                 0                 0         0                  0   
4                 0                 0         0                  0   
...             ...               ...       ...                ...   
32556             1                 0         0                  0   
32557             0                 0         0                  0   
32558             0                 0         0                  0   
32559             0                 0         0                  0   
32560             0                 0         0                  0   

       Married_civ_spouse  Married_spouse_absent  Never_married  Separated  \
0                       0                      0              1          0   
1                       1                      0              0          0   
2                       0                      0              0          0   
3                       1                      0              0          0   
4                       1                      0              0          0   
...                   ...                    ...            ...        ...   
32556                   1                      0              0          0   
32557                   1                      0              0          0   
32558                   0                      0              0          0   
32559                   0                      0              1          0   
32560                   1                      0              0          0   

       Widowed  
0            0  
1            0  
2            0  
3            0  
4            0  
...        ...  
32556        0  
32557        0  
32558        1  
32559        0  
32560        0  

[32561 rows x 63 columns]

In [89]:
min_max_scaler = preprocessing.MinMaxScaler()

In [90]:
x = df_menu
x = min_max_scaler.fit_transform(x)

In [91]:
y = df_target

In [92]:
dfx = pd.DataFrame(x)

In [93]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20)

In [94]:
dfy_train = pd.DataFrame(y_train)

In [95]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn import svm

In [96]:
clf = svm.SVC()

In [97]:
clf.fit(x_train, y_train)

/home/temporary/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC()

In [98]:
y_pred = clf.predict(x_test)

In [99]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

In [100]:
accuracy_score(y_test, y_pred)

0.8307999385843697

In [101]:
#OtherModel

In [102]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(x_train, y_train)

/home/temporary/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC(kernel='sigmoid')

In [103]:
y_pred = svclassifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[4236  751]
 [ 774  752]]
              precision    recall  f1-score   support

           0       0.85      0.85      0.85      4987
           1       0.50      0.49      0.50      1526

    accuracy                           0.77      6513
   macro avg       0.67      0.67      0.67      6513
weighted avg       0.76      0.77      0.77      6513



In [104]:
accuracy_score(y_test, y_pred)

0.7658529095654845

In [105]:
# save the model to disk

In [110]:
filename = 'census_class_model.sav'
pickle.dump(clf, open(filename, 'wb'))